/**:
  ros__parameters:
    voxel_size: 0.07
    # multi mapper
    # mapping_type: ["dynamic", "static_occupancy"]
    mapping_type: "static_tsdf" # ["dynamic", "static_occupancy"]

    # esdf settings
    esdf_mode: 1 # 0: 3d, 1: 2d

    # lidar settings
    use_lidar: true
    lidar_width: 1800
    lidar_height: 1800
    lidar_min_valid_range_m: 0.1
    lidar_max_valid_range_m: 50.0
    use_non_equal_vertical_fov_lidar_params: true

    # max_back_projection_distance: 30.0
 
    # min_angle_below_zero_elevation_rad: -0.9 #7 deg
    # max_angle_above_zero_elevation_rad: 0.9 # 52 deg 
    min_angle_below_zero_elevation_rad: -1.570796 # -90 deg
    max_angle_above_zero_elevation_rad: 1.570796 # 90 deg 

    # min_angle_below_zero_elevation_rad: -3.1
    # max_angle_above_zero_elevation_rad: 0.1
 
    # Map clearing settings
    map_clearing_radius_m: 20.0 # no map clearing if < 0.0
    map_clearing_frame_id: "base_link"
    layer_visualization_exclusion_radius_m: 30.0
    layer_visualization_exclusion_height_m: 4.0
    slice_visualization_side_length: 100.0
    maximum_sensor_message_queue_length: 30

    static_mapper:
      # freespace integrator
      projective_integrator_max_integration_distance_m: 15.0
      max_tsdf_distance_for_occupancy_m: 0.15

      max_unobserved_to_keep_consecutive_occupancy_ms: 200
      min_duration_since_occupied_for_freespace_ms: 250
      min_consecutive_occupancy_duration_for_reset_ms: 2000

      # check_neighborhood: true
      projective_integrator_truncation_distance_vox: 4.0
      lidar_projective_integrator_max_integration_distance_m: 25.0

      # Slice
      esdf_slice_height: 0.30
      esdf_slice_min_height: 0.25
      esdf_slice_max_height: 0.65

    dynamic_mapper:
      lidar_projective_integrator_max_integration_distance_m: 25.0
      projective_integrator_max_integration_distance_m: 25.0
      esdf_integrator_max_distance_m: 30.0
    #   # occupancy integrator
    #   projective_integrator_max_integration_distance_m: 15.0
    #   projective_integrator_truncation_distance_vox: 4.0

    #   # probabilities
    #   free_region_occupancy_probability: 0.2
    #   occupied_region_occupancy_probability: 0.9
    #   unobserved_region_occupancy_probability: 0.35
    #   occupied_region_half_width_m: 0.15

    #   # esdf integrator
    #   esdf_integrator_min_weight: 2.0
    #   esdf_integrator_max_distance_m: 30.0
    #   esdf_integrator_max_site_distance_vox: 5.0

    #   # occupancy decay integrator
    #   free_region_decay_probability: 0.55
    #   occupied_region_decay_probability: 0.25
